package models

import (
	"encoding/xml"
	"testing"

	"github.com/stretchr/testify/require"
)

func TestPlayerStats(t *testing.T) {
	xmlPlayerStats := "<stats><seedsSown>6077</seedsSown><itemsShipped>18012</itemsShipped><itemsCooked>47</itemsCooked><itemsCrafted>6492</itemsCrafted><chickenEggsLayed>888</chickenEggsLayed><duckEggsLayed>286</duckEggsLayed><cowMilkProduced>0</cowMilkProduced><goatMilkProduced>0</goatMilkProduced><rabbitWoolProduced>353</rabbitWoolProduced><sheepWoolProduced>0</sheepWoolProduced><cheeseMade>657</cheeseMade><goatCheeseMade>173</goatCheeseMade><trufflesFound>0</trufflesFound><stoneGathered>6682</stoneGathered><rocksCrushed>9144</rocksCrushed><dirtHoed>3854</dirtHoed><giftsGiven>249</giftsGiven><timesUnconscious>0</timesUnconscious><averageBedtime>2230</averageBedtime><timesFished>851</timesFished><fishCaught>928</fishCaught><bouldersCracked>1</bouldersCracked><stumpsChopped>0</stumpsChopped><stepsTaken>623565</stepsTaken><monstersKilled>1735</monstersKilled><diamondsFound>0</diamondsFound><prismaticShardsFound>0</prismaticShardsFound><otherPreciousGemsFound>5</otherPreciousGemsFound><caveCarrotsFound>0</caveCarrotsFound><copperFound>1272</copperFound><ironFound>1506</ironFound><coalFound>0</coalFound><coinsFound>0</coinsFound><goldFound>873</goldFound><iridiumFound>2318</iridiumFound><barsSmelted>0</barsSmelted><beveragesMade>2114</beveragesMade><preservesMade>1164</preservesMade><piecesOfTrashRecycled>419</piecesOfTrashRecycled><mysticStonesCrushed>1</mysticStonesCrushed><daysPlayed>344</daysPlayed><weedsEliminated>11</weedsEliminated><sticksChopped>0</sticksChopped><notesFound>20</notesFound><questsCompleted>73</questsCompleted><starLevelCropsShipped>0</starLevelCropsShipped><cropsShipped>7213</cropsShipped><itemsForaged>2050</itemsForaged><slimesKilled>691</slimesKilled><geodesCracked>297</geodesCracked><goodFriends>18</goodFriends><specificMonstersKilled><item><key><string>Green Slime</string></key><value><int>153</int></value></item><item><key><string>Bug</string></key><value><int>73</int></value></item><item><key><string>Duggy</string></key><value><int>9</int></value></item><item><key><string>Fly</string></key><value><int>45</int></value></item><item><key><string>Rock Crab</string></key><value><int>10</int></value></item><item><key><string>Grub</string></key><value><int>103</int></value></item><item><key><string>Stone Golem</string></key><value><int>33</int></value></item><item><key><string>Bat</string></key><value><int>35</int></value></item><item><key><string>Frost Bat</string></key><value><int>111</int></value></item><item><key><string>Frost Jelly</string></key><value><int>200</int></value></item><item><key><string>Dust Spirit</string></key><value><int>167</int></value></item><item><key><string>Ghost</string></key><value><int>25</int></value></item><item><key><string>Skeleton</string></key><value><int>45</int></value></item><item><key><string>Shadow Brute</string></key><value><int>43</int></value></item><item><key><string>Shadow Shaman</string></key><value><int>31</int></value></item><item><key><string>Lava Bat</string></key><value><int>36</int></value></item><item><key><string>Sludge</string></key><value><int>282</int></value></item><item><key><string>Lava Crab</string></key><value><int>10</int></value></item><item><key><string>Metal Head</string></key><value><int>26</int></value></item><item><key><string>Squid Kid</string></key><value><int>14</int></value></item><item><key><string>Big Slime</string></key><value><int>53</int></value></item><item><key><string>Mummy</string></key><value><int>10</int></value></item><item><key><string>Serpent</string></key><value><int>116</int></value></item><item><key><string>Iridium Crab</string></key><value><int>18</int></value></item><item><key><string>Carbon Ghost</string></key><value><int>20</int></value></item><item><key><string>Iridium Bat</string></key><value><int>64</int></value></item></specificMonstersKilled><GoodFriends>18</GoodFriends><CropsShipped>7213</CropsShipped><ItemsForaged>2050</ItemsForaged><GeodesCracked>297</GeodesCracked><SlimesKilled>691</SlimesKilled><StarLevelCropsShipped>0</StarLevelCropsShipped><StoneGathered>6682</StoneGathered><QuestsCompleted>73</QuestsCompleted><FishCaught>928</FishCaught><NotesFound>20</NotesFound><SticksChopped>0</SticksChopped><WeedsEliminated>11</WeedsEliminated><DaysPlayed>344</DaysPlayed><BouldersCracked>1</BouldersCracked><MysticStonesCrushed>1</MysticStonesCrushed><GoatCheeseMade>173</GoatCheeseMade><CheeseMade>657</CheeseMade><PiecesOfTrashRecycled>419</PiecesOfTrashRecycled><PreservesMade>1164</PreservesMade><BeveragesMade>2114</BeveragesMade><BarsSmelted>0</BarsSmelted><IridiumFound>2318</IridiumFound><GoldFound>873</GoldFound><CoinsFound>0</CoinsFound><CoalFound>0</CoalFound><IronFound>1506</IronFound><CopperFound>1272</CopperFound><CaveCarrotsFound>0</CaveCarrotsFound><OtherPreciousGemsFound>5</OtherPreciousGemsFound><PrismaticShardsFound>0</PrismaticShardsFound><DiamondsFound>0</DiamondsFound><MonstersKilled>1735</MonstersKilled><StepsTaken>623565</StepsTaken><StumpsChopped>0</StumpsChopped><TimesFished>851</TimesFished><AverageBedtime>2230</AverageBedtime><TimesUnconscious>0</TimesUnconscious><GiftsGiven>249</GiftsGiven><DirtHoed>3854</DirtHoed><RocksCrushed>9144</RocksCrushed><TrufflesFound>0</TrufflesFound><SheepWoolProduced>0</SheepWoolProduced><RabbitWoolProduced>353</RabbitWoolProduced><GoatMilkProduced>0</GoatMilkProduced><CowMilkProduced>0</CowMilkProduced><DuckEggsLayed>286</DuckEggsLayed><ItemsCrafted>6492</ItemsCrafted><ChickenEggsLayed>888</ChickenEggsLayed><ItemsCooked>47</ItemsCooked><ItemsShipped>18012</ItemsShipped><SeedsSown>6077</SeedsSown></stats>"
	var playerStats PlayerStats

	err := xml.Unmarshal([]byte(xmlPlayerStats), &playerStats)

	require.NoError(t, err)
	require.Equal(t, 6077, playerStats.SeedsSown)
	require.Equal(t, 18012, playerStats.ItemsShipped)
	require.Equal(t, 6492, playerStats.ItemsCrafted)
	require.Equal(t, 47, playerStats.ItemsCooked)
	require.Equal(t, 888, playerStats.ChickenEggsLayed)
	require.Equal(t, 286, playerStats.DuckEggsLayed)
	require.Equal(t, 0, playerStats.CowMilkProduced)
	require.Equal(t, 0, playerStats.GoatMilkProduced)
	require.Equal(t, 353, playerStats.RabbitWoolProduced)
	require.Equal(t, 0, playerStats.SheepWoolProduced)
	require.Equal(t, 657, playerStats.CheeseMade)
	require.Equal(t, 173, playerStats.GoatCheeseMade)
	require.Equal(t, 0, playerStats.TrufflesFound)
	require.Equal(t, 6682, playerStats.StoneGathered)
	require.Equal(t, 9144, playerStats.RocksCrushed)
	require.Equal(t, 3854, playerStats.DirtHoed)
	require.Equal(t, 249, playerStats.GiftsGiven)
	require.Equal(t, 0, playerStats.TimesUnconscious)
	require.Equal(t, 2230, playerStats.AverageBedtime)
	require.Equal(t, 851, playerStats.TimesFished)
	require.Equal(t, 928, playerStats.FishCaught)
	require.Equal(t, 1, playerStats.BouldersCracked2)
	require.Equal(t, 0, playerStats.StumpsChopped)
	require.Equal(t, 623565, playerStats.StepsTaken)
	require.Equal(t, 1735, playerStats.TotalMonstersKilled)
	require.Equal(t, 0, playerStats.DiamondsFound)
	require.Equal(t, 0, playerStats.PrismaticShardsFound)
	require.Equal(t, 5, playerStats.OtherPreciousGemsFound)
	require.Equal(t, 0, playerStats.CaveCarrotsFound)
	require.Equal(t, 1272, playerStats.CopperFound)
	require.Equal(t, 1506, playerStats.IronFound)
	require.Equal(t, 0, playerStats.CoalFound)
	require.Equal(t, 0, playerStats.CoinsFound)
	require.Equal(t, 873, playerStats.GoldFound)
	require.Equal(t, 2318, playerStats.IridiumFound)
	require.Equal(t, 0, playerStats.BarsSmelted)
	require.Equal(t, 2114, playerStats.BeveragesMade)
	require.Equal(t, 1164, playerStats.PreservesMade)
	require.Equal(t, 419, playerStats.PiecesOfTrashRecycled)
	require.Equal(t, 1, playerStats.MysticStonesCrushed)
	require.Equal(t, 344, playerStats.DaysPlayed)
	require.Equal(t, 11, playerStats.WeedsEliminated)
	require.Equal(t, 0, playerStats.SticksChopped)
	require.Equal(t, 20, playerStats.NotesFound)
	require.Equal(t, 73, playerStats.QuestsCompleted)
	require.Equal(t, 0, playerStats.StarLevelCropsShipped)
	require.Equal(t, 7213, playerStats.CropsShipped)
	require.Equal(t, 2050, playerStats.ItemsForaged)
	require.Equal(t, 691, playerStats.SlimesKilled)
	require.Equal(t, 297, playerStats.GeodesCracked)
	require.Equal(t, 18, playerStats.GoodFriends)
	require.Equal(t, 18, playerStats.GoodFriends)
	require.Equal(t, 7213, playerStats.CropsShipped)
	require.Equal(t, 2050, playerStats.ItemsForaged)
	require.Equal(t, 297, playerStats.GeodesCracked)
	require.Equal(t, 691, playerStats.SlimesKilled)
	require.Equal(t, 0, playerStats.StarLevelCropsShipped)
	require.Equal(t, 6682, playerStats.StoneGathered)
	require.Equal(t, 73, playerStats.QuestsCompleted)
	require.Equal(t, 928, playerStats.FishCaught)
	require.Equal(t, 20, playerStats.NotesFound)
	require.Equal(t, 0, playerStats.SticksChopped)
	require.Equal(t, 11, playerStats.WeedsEliminated)
	require.Equal(t, 344, playerStats.DaysPlayed)
	require.Equal(t, 1, playerStats.BouldersCracked)
	require.Equal(t, 1, playerStats.MysticStonesCrushed)
	require.Equal(t, 173, playerStats.GoatCheeseMade)
	require.Equal(t, 657, playerStats.CheeseMade)
	require.Equal(t, 419, playerStats.PiecesOfTrashRecycled)
	require.Equal(t, 1164, playerStats.PreservesMade)
	require.Equal(t, 2114, playerStats.BeveragesMade)
	require.Equal(t, 0, playerStats.BarsSmelted)
	require.Equal(t, 2318, playerStats.IridiumFound)
	require.Equal(t, 873, playerStats.GoldFound)
	require.Equal(t, 0, playerStats.CoinsFound)
	require.Equal(t, 0, playerStats.CoalFound)
	require.Equal(t, 1506, playerStats.IronFound)
	require.Equal(t, 1272, playerStats.CopperFound)
	require.Equal(t, 0, playerStats.CaveCarrotsFound)
	require.Equal(t, 5, playerStats.OtherPreciousGemsFound)
	require.Equal(t, 0, playerStats.PrismaticShardsFound)
	require.Equal(t, 0, playerStats.DiamondsFound)
	require.Equal(t, 1735, playerStats.TotalMonstersKilled2)
	require.Equal(t, 623565, playerStats.StepsTaken)
	require.Equal(t, 0, playerStats.StumpsChopped)
	require.Equal(t, 851, playerStats.TimesFished)
	require.Equal(t, 2230, playerStats.AverageBedtime)
	require.Equal(t, 0, playerStats.TimesUnconscious2)
	require.Equal(t, 249, playerStats.GiftsGiven)
	require.Equal(t, 3854, playerStats.DirtHoed)
	require.Equal(t, 9144, playerStats.RocksCrushed)
	require.Equal(t, 0, playerStats.TrufflesFound)
	require.Equal(t, 0, playerStats.SheepWoolProduced)
	require.Equal(t, 353, playerStats.RabbitWoolProduced)
	require.Equal(t, 0, playerStats.GoatMilkProduced)
	require.Equal(t, 0, playerStats.CowMilkProduced)
	require.Equal(t, 286, playerStats.DuckEggsLayed)
	require.Equal(t, 6492, playerStats.ItemsCrafted)
	require.Equal(t, 888, playerStats.ChickenEggsLayed)
	require.Equal(t, 47, playerStats.ItemsCooked)
	require.Equal(t, 18012, playerStats.ItemsShipped)
	require.Equal(t, 6077, playerStats.SeedsSown)
	counts := playerStats.MonstersKilled.Counts()
	require.Equal(t, 153, counts["Green Slime"])
	require.Equal(t, 73, counts["Bug"])
	require.Equal(t, 9, counts["Duggy"])
	require.Equal(t, 45, counts["Fly"])
	require.Equal(t, 10, counts["Rock Crab"])
	require.Equal(t, 103, counts["Grub"])
	require.Equal(t, 33, counts["Stone Golem"])
	require.Equal(t, 35, counts["Bat"])
	require.Equal(t, 111, counts["Frost Bat"])
	require.Equal(t, 200, counts["Frost Jelly"])
	require.Equal(t, 167, counts["Dust Spirit"])
	require.Equal(t, 25, counts["Ghost"])
	require.Equal(t, 45, counts["Skeleton"])
	require.Equal(t, 43, counts["Shadow Brute"])
	require.Equal(t, 31, counts["Shadow Shaman"])
	require.Equal(t, 36, counts["Lava Bat"])
	require.Equal(t, 282, counts["Sludge"])
	require.Equal(t, 10, counts["Lava Crab"])
	require.Equal(t, 26, counts["Metal Head"])
	require.Equal(t, 14, counts["Squid Kid"])
	require.Equal(t, 53, counts["Big Slime"])
	require.Equal(t, 10, counts["Mummy"])
	require.Equal(t, 116, counts["Serpent"])
	require.Equal(t, 18, counts["Iridium Crab"])
	require.Equal(t, 20, counts["Carbon Ghost"])
	require.Equal(t, 64, counts["Iridium Bat"])
}
